### ISSUE TITLE
Agnostic unit conversion backend

### ISSUE THREAD

**Issue by bekozi** [NCPP/ocgis#394]
who: @ocefpaf, @rsignell-usgs

https://github.com/SciTools/cf_units

**Comment by ocefpaf** [comment]
I am biased by recommending this change :wink: 

Bare in mind that we have this https://github.com/SciTools/cf_units/issues/30 limitation at the moment.

**Comment by bekozi** [comment]
Noted. Thanks for the heads up! It should be possible to make unit conversion agnostic to the library.

**Comment by ocefpaf** [comment]
Awesome! :+1:

**Comment by bekozi** [comment]
``cf_units`` and ``cfunits-python`` are both supported. There are few syntactical differences between the two software. In-place conversion support should be added for ``cf_units``.

**Comment by ocefpaf** [comment]
Awesome!  (You work fast! It is hard to keep up.)

**Comment by bekozi** [comment]
``cf_units`` made it easy! :+1:
