### ISSUE TITLE
Fix builds for conda-forge

### ISSUE THREAD

**Issue by bekozi** [NCPP/ocgis#415]
@ocefpaf has migrated the IOOS recipes to conda-forge. There are some outstanding test failures on the new CI. See https://github.com/conda-forge/staged-recipes/pull/159.

**Comment by bekozi** [comment]
Test failures are related to masked array changes in``numpy v1.11``. The changes only affected some tests checking NetCDF file equality. Need to tag a new bug fix release with the fixes.

**Comment by bekozi** [comment]
@ocefpaf, could you retry ``conda-forge`` builds using the ``ocgis`` branch ``i415-conda-forge``? I'm not quite sure how to navigate the PR chain. It'd be nice to fix any other issues on this before tagging. Thank you!

**Comment by ocefpaf** [comment]
Sure. Hold on...

**Comment by bekozi** [comment]
Merged to ``master``.
