### ISSUE TITLE
Use representative lat/lon for rotated pole coordinate systems

### ISSUE THREAD

**Issue by bekozi** [NCPP/ocgis#463]
* Configurable parameter to indicate if representative coordinates should be used. 
* Not sure if this should default to true. I'm inclined to say it should be the default to reduce work required to get coordinates (avoid rotated pole transformation).
* Coordinate changes can be done on the dimension map.
* Coordinate system metadata on the input should not be modified. In other words, it should keep the rotated pole as the default coordinate system in CF grid mapping indicates as much.

Related to https://github.com/bird-house/flyingpigeon/issues/197.

Ping @nilshempelmann, @cehbrecht.

**Comment by nilshempelmann** [comment]
If input data are stored in an archive, it is not recommended to change the input

**Comment by bekozi** [comment]
> If input data are stored in an archive, it is not recommended to change the input

No data should have to change. It will be a different way (improved way) to interpret rotated pole.

**Comment by bekozi** [comment]
Available in `master`.
