### ISSUE TITLE
Writing compressed netCDF files?

### ISSUE THREAD

**Issue by aaschwanden** [NCPP/ocgis#473]
Hi, 

I'm extracting large data sets using a shape file from even larger data sets. Is there a way to write compressed netCDF files directly via ocgis.OcgOperations() ?

**Comment by bekozi** [comment]
Hi @aaschwanden, you can use `output_format_options`: http://ocgis.readthedocs.io/en/latest/operations.html#output-format-options

For what you need it would look like:
```python
options = {'variable_kwargs': {'zlib': True, 'complevel': 4}}
```
Let me know if it doesn't work for you.

**Comment by aaschwanden** [comment]
Great, thanks. I’m at the AGU conference right now, I’ll try it out when I get back.

**Comment by aaschwanden** [comment]
Hi,

this worked for me.

Thanks,

Andy

**Comment by bekozi** [comment]
:+1:
