### ISSUE TITLE
OcgOperations output_format=netcdf-esmf-unstruct not supported

### ISSUE THREAD

**Issue by rokuingh** [NCPP/ocgis#491]
OcgOperations output_format=keep_auxiliary_files=False is not supported, executions ends with the following traceback:

ocgis.exc.DefinitionValidationError: OcgOperations validation raised an exception on the argument/operation "output_format" with the message: Valid arguments are: ['shp', 'csv', 'csv-shp', 'ocgis', 'geojson', 'nc', 'meta-json', 'meta-ocgis'].

**Comment by bekozi** [comment]
Netcdf writing now allows ESMF Unstruct output while maintaining conversion from UGRID.

Merged to `master`.
